### ISSUE TITLE
Changes! Please check these changes and addition to the system.

### ISSUE THREAD

**Issue by Xednom** [imond12345678/RVL-Management-System-apprentice#1]
Raymond Check mo yung mga binabago at dinagdag kong mga forms nasa Main form na sila, mag post ka or reply ka dito sa issue na ito pag may mga hindi ka nakita. Please paki check lahat ng forms hah?

![screenshot_58](https://cloud.githubusercontent.com/assets/7580943/23090738/20f24d2c-f5e0-11e6-9ef1-12808b3d1ffe.png)

_Piso

**Comment by Xednom** [comment]
Aim: Views with search functions and Delete in all forms. Check if all necessary forms have been added.

**Comment by imond12345678** [comment]
Done With the constraints in 16 forms check for the commitments and changes

**Comment by Xednom** [comment]
Will check later or tomorrow, will post another issue if something comes up 👍
